# Generated by Django 3.2.16 on 2022-10-06 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=200)),
                ('price', models.FloatField(default=None)),
                ('thumbnail', models.ImageField(default=None, upload_to='')),
                ('category', models.CharField(default=None, max_length=200)),
                ('quantity', models.CharField(default='In stock', max_length=200)),
                ('description', models.TextField(default=None)),
                ('update_at', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default=None, upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.products')),
            ],
        ),
    ]
