# Generated by Django 3.2.16 on 2022-10-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20221010_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='frontend.products'),
        ),
    ]
