# Generated by Django 3.2.16 on 2022-10-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_images_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='products',
            name='thumbnail',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
