# Generated by Django 3.2.16 on 2022-10-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20221010_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
    ]
